version: '3.9'
services:
  db:
    image: postgres:13.4-alpine3.14
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 2s
      start_period: 10s
  backoffice:
    build:
      dockerfile: ./docker/backoffice/Dockerfile
      context: .
    volumes:
      - .:/app:cached
    environment:
      - DB_URL=host=db user=postgres password=password dbname=postgres port=5432 sslmode=disable
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  database_data:
